# Generated by Django 3.1 on 2020-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20200915_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
