# Generated by Django 3.1 on 2020-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_schedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bookedTickets',
            field=models.CharField(default='', max_length=100),
        ),
    ]
