# Generated by Django 3.1 on 2020-11-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20201031_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bookedTickets',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default=0, max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_ticket_details', to='bus.ticket')),
            ],
        ),
    ]
