# Generated by Django 3.1 on 2020-11-02 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_auto_20201102_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 15, 15, 26, 786630, tzinfo=utc)),
        ),
    ]
